#!/usr/bin/env php
<?php

require_once __DIR__.'/vendor/autoload.php';

$app = new Silex\Application();

require __DIR__.'/app/app.php';

$console = require __DIR__.'/app/console.php';
$console->run();

